script: npm run build
language: node_js
node_js:
  - "11.6.0"
install:
  - npm install
#deploy:
#  local_dir: public
#  provider: pages
#  fqdn: koodiklinikka.fi
#  skip_cleanup: true
#  github_token: "$GITHUB_TOKEN"
#  repo: koodiklinikka/koodiklinikka.github.io
#  target_branch: master
#  on:
#    branch: master
#after_success:
#  - chmod ugo+x ./deploy-surge.sh
#  - "./deploy-surge.sh"
